spring.application.name=wallet

server.port=8080

# PostgreSQL ???????????
spring.datasource.url=jdbc:postgresql://localhost:5433/wallet
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=wallet_user
spring.datasource.password=wallet_pass


# JPA ?????????
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# spring.flyway.baseline-on-migrate=true