#??? ?????? ?????????? (??? ?????)
spring.application.name=wallet

# ?? ????????? ???????
# ????????? ????, ?? ??????? ????? ???????? ???? ??????????
# 8080 - ??? ??????????? ???? ??? ???-??????????
# ????? ??????? ?????????? ????? ???????? ?? ??????: http://localhost:8080
server.port=8080

# ?? ????????? ??????????? ? ???? ??????
# URL ??????????? ? ???? ?????? H2
# jdbc:h2: - ??? ???????? ??????????? ? H2
# mem: - ????????, ??? ???? ?????? ????? ???????? ? ??????????? ?????? (????? ??????)
# walletdb - ??? ???????? ????? ???? ??????
# ?????: ??? ??? ???? ? ??????, ??? ??????????? ?????????? ??? ?????? ????????
spring.datasource.url=jdbc:h2:mem:walletdb

# ?????-???????, ??????? ?????, ??? ???????? ? ????? H2
# ??? ??? "??????????" ????? Java ? ????? ??????
spring.datasource.driverClassName=org.h2.Driver

# ??? ???????????? ??? ??????????? ? ???? ??????
# sa - ??? ??????????? ???????????? H2 (system administrator)
spring.datasource.username=sa

# ?????? ??? ??????????? ? ???? (?????? - ???????? ??? H2)
spring.datasource.password=

# ?? ????????? ???-??????? H2 (????? ???????!)
# ???????? ???-????????? ??? ????????? ???? ?????? ????? ???????
# ??? ??? "??????", ????? ??????? ????? ????????? ? ???? ? ??????? ???????
spring.h2.console.enabled=true

# ?????, ?? ???????? ????? ???????? ??????? H2
# ????? ??????? ?????????? ????????? ??????? ? ??????:
# http://localhost:8080/h2-console
spring.h2.console.path=/h2-console

# ? ????????? JPA (??? SPRING ????? ???????? ? ?????)
# ?????????? ? ??????? IDEA ??? SQL ???????, ??????? Hibernate ?????????? ? ????
# ??? ???????? ??????, ??? ??????? ?????????? ??? ??????????/?????? ??????
# ????????, ????? ?? ????????? ??????????, ??????? INSERT ??????
spring.jpa.show-sql=true

# ????? ?????? ????????? ??? ??????!
# ddl-auto = Data Definition Language automatic
# update - ????????: "???????? ?? ??? Java-?????? ? ?????? ??? ??? ??????? ?????????????"
# ???? ??????? ??? ???? - ?????? ?? ?????????
# ?????? ????????: create (????????????????), validate (?????? ?????????), none (?????? ?? ??????)
spring.jpa.hibernate.ddl-auto=update

# ????????? Thymeleaf (????????? ??? ??? ??????????)
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html